// Generated by CoffeeScript 1.7.1
(function() {
  var Memcached, memcache;

  memcache = require("memcache");

  Memcached = (function() {
    Memcached.prototype.CACHE_KEY = "latest-timeline";

    function Memcached(host, port) {
      this.client = new memcache.Client(port, host);
      this.client.connect();
    }

    Memcached.prototype.get = function(callback) {
      return this.client.get(this.CACHE_KEY, function(error, result) {
        return callback(error, JSON.parse(result));
      });
    };

    Memcached.prototype.set = function(feed) {
      return this.client.set(this.CACHE_KEY, JSON.stringify(feed), function(e, r) {
        if (e) {
          return console.log("set error: " + e);
        }
      });
    };

    return Memcached;

  })();

  module.exports = Memcached;

}).call(this);
