// Generated by CoffeeScript 1.7.1
(function() {
  var Memcached, memClient;

  Memcached = require("../memcached-wrapper");

  memClient = new Memcached("localhost", 11211);

  module.exports = function(req, res) {
    return res.render('rss', memClient.get());
  };

}).call(this);
